## 1. Hacker Rank Challenge

he provided code stub will read in a dictionary containing key/value pairs of name:[marks] for a list of students. Print the average of the marks array for the student name provided, showing 2 places after the decimal.

[Hacker Link](https://www.hackerrank.com/challenges/finding-the-percentage/problem?isFullScreen=true)

In [4]:
 marks = {'Krishna': [67.0, 68.0, 69.0], 'Arjun': [70.0, 78.0, 79.0],'Shankar': [87.0, 88.0, 89.0]}
 print(marks)

{'Krishna': [67.0, 68.0, 69.0], 'Arjun': [70.0, 78.0, 79.0], 'Shankar': [87.0, 88.0, 89.0]}


In [5]:
for key,value in marks.items():
  if key == 'Arjun':
    print(sum(value)/3)

75.66666666666667


In [7]:

if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()

def calculate(student_marks, name):
  print('Marks and Name', student_marks, query_name)
  result = 0
  for key,value in student_marks.items():
    print('Within For Loop - Key and Value', key, value)
    if key == query_name:
      result = sum(value)/3
      break
  return result

a = calculate(student_marks, query_name)
print(format(a,'.2f'))


3
Krishna 67 68 69
Arjun 70 98 63
Malika 52 56 60
Malika
Marks and Name {'Krishna': [67.0, 68.0, 69.0], 'Arjun': [70.0, 98.0, 63.0], 'Malika': [52.0, 56.0, 60.0]} Malika
Within For Loop - Key and Value Krishna [67.0, 68.0, 69.0]
Within For Loop - Key and Value Arjun [70.0, 98.0, 63.0]
Within For Loop - Key and Value Malika [52.0, 56.0, 60.0]
56.00


In [ ]:
x = 1
n = int(input())
while x <=n:
  print(x, end='')
  x += 1

## 2. Hackerrank Numpy Arrays

Print the reverse NumPy array with type float.

[Hack Link](https://www.hackerrank.com/challenges/np-arrays/problem?utm_campaign=challenge-recommendation&utm_medium=email&utm_source=24-hour-campaign%5Blink)

In [ ]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    toarr = numpy.array(arr, dtype=numpy.float32)
    return(toarr[::-1])

arr = input().strip().split(' ')
result = arrays(arr)
print(result)


1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [ ]:
import numpy
# Enter your code here. Read input from STDIN. Print output to STDOUT

data = list(map(int, input().split()))
data = numpy.array(data, int)
return(numpy.reshape(data, (3,3)))

data.shape = (3,3)
print (data)




1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy

my__1D_array = numpy.array([1, 2, 3, 4, 5, 6])
print (my__1D_array.shape)
my__1D_array.shape = (3, 3)
print (my__1D_array)



(6,)
[[1 2]
 [3 4]
 [5 6]]


##3. Hackerrank Transpose and Flatten
Hackerrank Challenge [here](https://www.hackerrank.com/challenges/np-transpose-and-flatten/problem?utm_campaign=challenge-recommendation&utm_medium=email&utm_source=24-hour-campaign)

In [ ]:
string = " hello world is the first code of first every programmer"
print(string.find("first"))

20


In [ ]:
list1 = [[1, 2],[3,4],[5,6]]
list2 = [[7],[8],[9],[10],[11],[12]]

new_list = []

for item1 in list1:
    for item2 in list2:
        new_list.append([item1, item2])

print(new_list)

<class 'list'>


##4. Hackerrank Zeros and Ones

[Hack Link](https://www.hackerrank.com/challenges/np-zeros-and-ones/problem?utm_campaign=challenge-recommendation&utm_medium=email&utm_source=24-hour-campaign)

In [ ]:
import numpy as np

shape = list(map(int, input().split()))
print(shape)

print(np.zeros(shape, dtype=int))
print(np.ones(shape, dtype=int))

In [ ]:
def addition(n):
    return n + n

# We double all numbers using map()
numbers = (1, 2, 3, 4)
result = map(addition, numbers)
#print(list(result))
print(list(result))

(2, 4, 6, 8)


In [ ]:
engagement = {'acct': '0', 'utc_date': '2015-01-09', 'num_courses_visited': '1.0', 'total_minutes_visited': '11.6793745', 'lessons_completed': '0.0', 'projects_completed': '0.0'}
print(engagement) #{'Ghana', 'USA', 'Ukraine', 'Nigeria'}

{'acct': '0', 'utc_date': '2015-01-09', 'num_courses_visited': '1.0', 'total_minutes_visited': '11.6793745', 'lessons_completed': '0.0', 'projects_completed': '0.0'}


In [ ]:
List_Of_Games = [
    {
        "Name":"CyberPunk 2077",
        "Username": "iDontPlayCyberPunk"
    },
    {
        "Name": "Call Of Duty: Warzone",
        "Username": "minininja"
    },
    {
        "Name": "Counter Strike: Global Offensive",
        "Username": "the_brave_gamer"
    },
    {
        "Name": "Valorant",
        "Username": "thebravegamer#askmeforusername"
    },
    {
        "Name": "Assassin's Creed Valhalla",
        "Username": "CompetetiveNahiKhelta"
    },
]
# if List_Of_Games["Name"] == "CyberPunk 2077":
#     print("It's full of bugs but still I Play Pirated Game.")

for i in range(len(List_Of_Games)):
    if List_Of_Games[i]["Name"] == "CyberPunk 2077":
        print("It's full of bugs but still I Play Pirated Game.")

It's full of bugs but still I Play Pirated Game.


## Random Phrase Generator

In [ ]:
import random

# Take from the 50 of the least used english words from https://www.yourdictionary.com/articles/rare-words-useful-know
# Make them into set of 4 tuples. Feel free to create any number of tuples

lest_used_words_1 = ("2", "4", "8", "6", "5", "3")
lest_used_words_2 = ("runs", "hits", "jumps", "drives", "barfs")
lest_used_words_3 = ("crazily.", "dutifully.", "foolishly.", "merrily.", "occasionally.")
lest_used_words_4 = ("adorable", "clueless", "dirty", "odd", "stupid")

num = random.randrange(0,6)
print(num)
print (nouns[num] + ' ' + verbs[num] + ' ' + adv[num] + ' ' + adj[num])

4
monkey barfs occasionally. stupid


In [ ]:
from wonderwords import RandomWord

r = RandomWord()

# generate a random word
r.word()
print('Simple Random Word', r)

# random word that starts with a and ends with en
#r.word(starts_with="a", ends_with="en")
print("Start with 'a' end with 'en':- ", r.word(starts_with="a", ends_with="en"))

# generate a random noun or adjective, by default all
print("Word with parts of speech are included :- ",r.word(sinclude_parts_of_speech=["nouns", "adjectives"]))


# you can combine multiple filtering options
r.word(starts_with="ru", word_max_length=10, include_parts_of_speech=["verbs"])

Simple Random Word <wonderwords.random_word.RandomWord object at 0x7dbd460f1de0>
Start with 'a' end with 'en':-  abdomen
Word with parts of speech are included :-  chick


In [ ]:
# generate a random word between the length of 3 and 8 characters
print("Random word between the length of 3 and 8 characters :- ",r.word(word_min_length=8, word_max_length=12))

# generate a random word with a custom regular expression
print("Random word with a custom regular expression :- ",r.word(regex=".*a"))


Random word between the length of 3 and 8 characters :-  endorsement
Random word with a custom regular expression :-  tiara


In [ ]:
# you can combine multiple filtering options
print("Random word by combining multiple filtering options :- ",r.word(starts_with="s", word_min_length=5, word_max_length=10, include_parts_of_speech=["nouns", "adjectives","verbs"]))

Random word by combining multiple filtering options :-  strength


##5. The-minion-game


---
*Solved*.

[Hackerrank Challenge](https://www.hackerrank.com/challenges/the-minion-game/problem?isFullScreen=true )

In [ ]:
## INITIAL TRIES ##

string = "JAPAN"
kevin_vow= ([char for char in string if char.lower() in {'a','e','i','o','u'}])
stuart_con = ([char for char in string if char.isalpha() and char.lower() not in {'a','e','i','o','u'}])
print(kevin_vow)
print(stuart_con)

['A', 'A']
['J', 'P', 'N']


In [ ]:
string[::-1]

'ANANAB'

In [ ]:
vowels = ["A","E","I","O","U"]
stuart = 0
kevin = 0
for pos,letter in enumerate(string,start=1):
  print('pos', pos)
  if letter in vowels:
      print('Vowel Pos', pos)
      kevin+=pos
  else:
      stuart+=pos
if stuart > kevin:
    print(f"Stuart {stuart}")
elif kevin > stuart:
    print(f"Kevin {kevin}")
else:
    print("Draw")




pos 1
pos 2
Vowel Pos 2
pos 3
pos 4
Vowel Pos 4
pos 5
Stuart 9


##6. 'Merge the Tools' Challenge

Consider the following:

A string, , of length  where .
An integer, , where  is a factor of .
We can split  into  substrings where each subtring, , consists of a contiguous block of  characters in . Then, use each  to create string  such that:

The characters in  are a subsequence of the characters in .
Any repeat occurrence of a character is removed from the string such that each character in  occurs exactly once. In other words, if the character at some index  in  occurs at a previous index  in , then do not include the character in string
Given  and , print  lines where each line  denotes string .


*Solved*.
[Challenge Link](https://www.hackerrank.com/challenges/merge-the-tools/problem?utm_campaign=challenge-recommendation&utm_medium=email&utm_source=24-hour-campaign
)

In [ ]:
string = 'AABCAAADA'
n = 3
u = 0

parts = [string[i:i+n] for i in range(0, len(string), n)]

for part in parts:
    new_part = ""
    for j in range(len(part)):
        # print("j", j)
        # print("part[j] =",part[j])
        # print('part[j-1] =',part[j-1])
        if j == 0 or part[j] != part[j-1] and part[j] not in new_part:
            new_part += part[j]
    print(new_part)

AB
CA
AD


In [ ]:
input_numbers = input('Please provide input values : ')
#Input example -- 1 5 6 7 9 -9 or 5 5 5 5
val = list(map(int, input_numbers.split()))
#val = val = [1, 2, 3, 4, 5, -9] # Smple Values
if all([True if i>0 else False for i in val]):
  res=any([True if str(i)==str(i)[::-1] else False for i in val])
else:
  res=False
print(res)


Please provide input values : 5 5 5 5 5
True


In [ ]:
#PYTHON eval() function
x=str(print(2 + 3))
eval(x)
eval(str((2+58)))

5


NameError: name 'apple' is not defined

##7. Plus Minus

Given an array of integers, calculate the ratios of its elements that are positive, negative, and zero. Print the decimal value of each fraction on a new line with  places after the decimal.
[Hacker Rank Link](https://www.hackerrank.com/challenges/plus-minus/problem?isFullScreen=false)

In [ ]:
arr=[-4, 3, -9, 0, 4, 1]
p,n,z=0,0,0
for i in arr:
    if i >=1:
      p +=1
    elif i <= 1 and i != 0:
      n +=1
    else:
      z +=1
print("{:.6f}".format(p/len(arr)))
print("{:.6f}".format(n/len(arr)))
print("{:.6f}".format(z/len(arr)))

## *********************************************
## USING LIST COMPREHENSIONS
## *********************************************
arr = [-4, 3, -9, 0, 4, 1]

p = sum(1 for i in arr if i > 0)
n = sum(1 for i in arr if i < 0)
z = sum(1 for i in arr if i == 0)

print("{:.6f}".format(p / len(arr)))
print("{:.6f}".format(n / len(arr)))
print("{:.6f}".format(z / len(arr)))


3 2 1
0.5
0.500000
0.333333
0.166667


##8. Hackerrank Nested Lists
Given the names and grades for each student in a class of  students, store them in a nested list and print the name(s) of any student(s) having the second lowest grade.

[Hack Link](https://www.hackerrank.com/challenges/nested-list/problem?isFullScreen=false)

In [ ]:
## FIRST LET US LEARN HOW TO CREATE NESTED LIST

# Initialize an empty list to store the final output
my_list = []

# Initialize an empty temporary list to store each sub-list
temp_list = []

# Take input from the user for the number of sub-lists
n = int(input('Enter the number of sub-lists: '))

# Loop over the range of n to take input for each sub-list
for i in range(n):

    # Loop over the range of 2 to take input for each element in the sub-list
    for j in range(2):

        # Take input from the user for the current element
        temp_list.append(input())

    # Append the current sub-list to the final list
    my_list.append(temp_list)

    # Reset the temporary list to an empty list for the next iteration
    temp_list = []

# Print the final output
print(my_list)

Enter the number of sub-lists: 3
3
3
4
5
6
7
[['3', '3'], ['4', '5'], ['6', '7']]


In [ ]:
records =[['A', 20],['B',50],['C', 50]]
records.sort(key=lambda x:x[1])
print(records)

[['A', 20], ['B', 50], ['C', 50]]


## Fibonacci Series

In [ ]:
num = 10
n1, n2 = 0, 1
fib_l=[n1,n2]
#print("Fibonacci Series:", n1, n2, end=" ")
for i in range(2, num):
    n3 = n1 + n2
    n1 = n2
    n2 = n3
    #print(n3, end=" ")
    fib_l.append(n3)
#print("\n")
print(fib_l)


[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [ ]:
l = list(range(10))
l = list(map(lambda x:x*x, l))
print(l)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
l = list(filter(lambda x: x > 10 and x < 80, l))
print(l)

[16, 25, 36, 49, 64]


## Validating Email Addresses : Use Regex pkg

In [ ]:
import re

def is_valid_email(email):
    # Define a regular expression for basic email validation
    regex = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{3,}$'
    return re.match(regex, email) is not None

# Example usage
email = "example@example.com"
print(f"Is the email '{email}' valid? {is_valid_email(email)}")

# Testing with various email addresses
emails = [
    "user@example.com",
    "user.name+tag+sorting@example.com",
    "user_name@example.com",
    "user-name@example.co.uk",
    "user.name@sub.example.com",
    "user@example", # Invalid
    "user@.com",    # Invalid
    "user@com",     # Invalid
    "@example.com", # Invalid
    "user@",        # Invalid
    "user@ example.com", # Invalid
]

for email in emails:
    print(f"Is the email '{email}' valid? {is_valid_email(email)}")


Is the email 'example@example.com' valid? True
Is the email 'user@example.com' valid? True
Is the email 'user.name+tag+sorting@example.com' valid? True
Is the email 'user_name@example.com' valid? True
Is the email 'user-name@example.co.uk' valid? False
Is the email 'user.name@sub.example.com' valid? True
Is the email 'user@example' valid? False
Is the email 'user@.com' valid? False
Is the email 'user@com' valid? False
Is the email '@example.com' valid? False
Is the email 'user@' valid? False
Is the email 'user@ example.com' valid? False


##9. Text Wrap
You are given a string *s* and width *w*.
Your task is to wrap the string into a paragraph of width *w*.

[Hack Link](https://www.hackerrank.com/challenges/text-wrap/problem?utm_campaign=challenge-recommendation&utm_medium=email&utm_source=24-hour-campaign)

In [ ]:
import textwrap

string = "ABCDEFGHIJKLIMNOQRSTUVWXYZ"
max_width = 4

for i in range(0,len(string),max_width):
    result = (string[i:i+max_width])
    print(result)

ABCD
EFGH
IJKL
IMNO
QRST
UVWX
YZ


In [ ]:
def wrap(string, max_width):
  return (textwrap.fill(string,max_width))

print(wrap('ABCDEFGHIJKLIMNOQRSTUVWXYZ',4))

ABCD
EFGH
IJKL
IMNO
QRST
UVWX
YZ
